/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControlRegistroSalida;
import Controlador.UtilidadHora;
import co.edu.modelo.Personas;
import co.edu.modelo.Programas;
import co.edu.modelo.RegistroEntradaSalida;
import co.edu.univalle.persistencia.DAOFactory;
import co.edu.univalle.persistencia.EntityManagerHelper;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;

/**
 *
 * @author Alejandra Becerra
 */
public class RegistroSalida extends javax.swing.JFrame implements Runnable{
    Thread hilo = new Thread(this);
    String hora;
    ControlRegistroSalida cs;
   
    Personas p;
    Programas pr;
   
    boolean existeSalida=false;
    int documento;
    public RegistroSalida() {
        initComponents();
        hilo.start();
        jlMensaje.setVisible(false);
        vaciar();
        setVisible(true);
    }private void mensaje(String mensaje){
        jlMensaje.setVisible(true);
        jlMensaje.setText(mensaje);
    }
    private void hora(){
        Calendar calend = new GregorianCalendar();
        Calendar c = Calendar.getInstance();
        String minutos =  ""+calend.get(c.MINUTE);      
        String segundos =  ""+calend.get(c.SECOND);
        if(minutos.length()==1){
           minutos = 0 + minutos; 
        }
        if(segundos.length()==1){
           segundos = 0 + segundos; 
        } 

        hora =""+calend.get(c.HOUR_OF_DAY)+":"+minutos+":"+segundos;      
    }
    private void vaciar(){
        jtCodEstudiante.setText("");
        jLNombre.setText("");
        jlCargo.setText("");
        jlCarrera.setText("");
        jlFechaEntrada.setText("");
        jlRegHoraEntrada.setText("");
    }
    public void modificar (String hora) throws Exception{
        Date auxHora = null;
        RegistroEntradaSalida regSalida = DAOFactory.getRegistroEntradaSalidaDAO().consultarID(cs.getCodigo());
        SimpleDateFormat formato = new SimpleDateFormat("HH:mm:ss");
        auxHora = formato.parse(hora);
        regSalida.setHoraSalida(auxHora);
            
        EntityManagerHelper.beginTransaction();
        DAOFactory.getRegistroEntradaSalidaDAO().modificar(regSalida);
        EntityManagerHelper.commit();
        EntityManagerHelper.closeEntityManager();
           
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlHora1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jlHora = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jlCarrera = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jlFechaEntrada = new javax.swing.JLabel();
        jlCargo = new javax.swing.JLabel();
        jlMensaje = new javax.swing.JLabel();
        jLNombre = new javax.swing.JLabel();
        jlRegHoraEntrada = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtCodEstudiante = new javax.swing.JTextField();
        jLBuscar = new javax.swing.JButton();
        jLCerrar = new javax.swing.JButton();
        jLFondo2 = new javax.swing.JLabel();
        jL_fondo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/descarga.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondorojo2.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, -1, 60));

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(175, 50, 75));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SALIDA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 370, 70));

        jlHora1.setFont(new java.awt.Font("Yu Gothic UI", 0, 30)); // NOI18N
        jlHora1.setText("HH:MM:SS");
        jPanel1.add(jlHora1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 550, 160, 80));

        jLabel11.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel11.setText("Cargo:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 90, 50));

        jlHora.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imgHora.png"))); // NOI18N
        jlHora.setBorderPainted(false);
        jlHora.setContentAreaFilled(false);
        jlHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscuchaHora(evt);
            }
        });
        jPanel1.add(jlHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 560, 230, 60));

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel12.setText("Carrera:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 90, 50));

        jlCarrera.setFont(new java.awt.Font("Yu Gothic UI", 0, 16)); // NOI18N
        jlCarrera.setText("DEPENDE");
        jPanel1.add(jlCarrera, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 390, 250, 50));

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel14.setText("Fecha entrada");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 130, 50));

        jlFechaEntrada.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jlFechaEntrada.setText("Fecha");
        jPanel1.add(jlFechaEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 440, 120, 50));

        jlCargo.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jlCargo.setText("cargo");
        jPanel1.add(jlCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 250, 50));

        jlMensaje.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        jlMensaje.setForeground(new java.awt.Color(204, 0, 0));
        jlMensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlMensaje.setText("mensaje");
        jPanel1.add(jlMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 460, 50));

        jLNombre.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLNombre.setText("Nombre");
        jPanel1.add(jLNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 250, 50));

        jlRegHoraEntrada.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jlRegHoraEntrada.setText("Hora");
        jPanel1.add(jlRegHoraEntrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 490, 210, 50));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel2.setText("Documento:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 110, 50));

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel13.setText("Hora entrada:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 490, 130, 50));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel4.setText("Nombre:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 90, 50));

        jtCodEstudiante.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jPanel1.add(jtCodEstudiante, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 200, 40));

        jLBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imgBuscar.png"))); // NOI18N
        jLBuscar.setBorderPainted(false);
        jLBuscar.setContentAreaFilled(false);
        jLBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscuchaBuscar(evt);
            }
        });
        jPanel1.add(jLBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 130, 60));

        jLCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imgCerrar.png"))); // NOI18N
        jLCerrar.setBorderPainted(false);
        jLCerrar.setContentAreaFilled(false);
        jLCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscuchaCerrar(evt);
            }
        });
        jPanel1.add(jLCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 650, 180, 60));

        jLFondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoSalida.jpg"))); // NOI18N
        jPanel1.add(jLFondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 510, 520));

        jL_fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoSalida.jpg"))); // NOI18N
        jPanel1.add(jL_fondo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, -1));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(518, 669));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void EscuchaHora(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscuchaHora
        try {
            if (!"".equals(jLNombre.getText())) {
                if (existeSalida == false) {
                    String hora = UtilidadHora.getinstance().getHora();
                    modificar(hora);
                }
                vaciar();
                new MostrarMensaje("Se ha registrado la Salida con exito",null,true);
            } else {
                mensaje("Debes buscar usuario");
            }
        } catch (Exception e) {
            System.out.println("ERROR " + e);
        }
    }//GEN-LAST:event_EscuchaHora

    private void EscuchaCerrar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscuchaCerrar
        dispose();
    }
//GEN-LAST:event_EscuchaCerrar

    private void EscuchaBuscar(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscuchaBuscar
        try {
            jlMensaje.setVisible(false);
            jlCarrera.setVisible(true);
            jLabel12.setVisible(true);
            documento=Integer.parseInt(jtCodEstudiante.getText());
            cs = new ControlRegistroSalida();
            
            p = DAOFactory.getPersona().consultarID(documento);
            pr = DAOFactory.getProgramasDAO().consultarID(p.getPrograma().hashCode());
            List<RegistroEntradaSalida> entradaSalida = DAOFactory.getRegistroEntradaSalidaDAO().consultarTodos();
            
            cs.registro(p,documento);

            ArrayList inf = cs.consultarTodo(p,pr,entradaSalida);

            jLNombre.setText((String) inf.get(0));
            jlCargo.setText((String) inf.get(1));

            if(inf.get(2).equals("")){
                jlCarrera.setVisible(false);
                jLabel12.setVisible(false);
            }else{
                jlCarrera.setText((String) inf.get(2));
            }

            jlRegHoraEntrada.setText((String) inf.get(3));
            jlFechaEntrada.setText((String) inf.get(4));

            if (!inf.get(5).equals("")) {
                mensaje("El Usuario ingresado, ya tiene registro de salida");
                existeSalida = true;
            }
        } catch (NumberFormatException e) {
            mensaje("El codigo debe ser numerico");
        } catch (Exception ex) {
            mensaje(ex.getMessage());
        }
    }//GEN-LAST:event_EscuchaBuscar

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jLBuscar;
    private javax.swing.JButton jLCerrar;
    private javax.swing.JLabel jLFondo2;
    public javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jL_fondo1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel jlCargo;
    public javax.swing.JLabel jlCarrera;
    public javax.swing.JLabel jlFechaEntrada;
    private javax.swing.JButton jlHora;
    public javax.swing.JLabel jlHora1;
    private javax.swing.JLabel jlMensaje;
    public javax.swing.JLabel jlRegHoraEntrada;
    public javax.swing.JTextField jtCodEstudiante;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
     Thread current = Thread.currentThread();
        while (current == hilo) {
            hora();
            jlHora1.setText(hora);
        }
    }
}
