/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.ControlReporte;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Kevin
 */
public class Reporte extends javax.swing.JFrame {

    ControlReporte cr;
    /**
     * Creates new form Reporte
     */
    String fechaInicial, fechaFinal;

    public Reporte() {
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Logo = new javax.swing.JLabel();
        Reporte = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        reporteEntrada = new javax.swing.JButton();
        reporteNovedad = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDateChooserInicial = new com.toedter.calendar.JDateChooser();
        jDateChooserFinal = new com.toedter.calendar.JDateChooser();
        mensaje = new javax.swing.JLabel();
        jL_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(null);

        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/descarga.png"))); // NOI18N
        jPanel1.add(Logo);
        Logo.setBounds(10, 0, 90, 90);

        Reporte.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        Reporte.setForeground(new java.awt.Color(175, 50, 75));
        Reporte.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Reporte.setText("REPORTE");
        jPanel1.add(Reporte);
        Reporte.setBounds(150, 40, 260, 48);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondorojo2.jpg"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(0, 100, 500, 60);

        reporteEntrada.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        reporteEntrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imgReporte.png"))); // NOI18N
        reporteEntrada.setContentAreaFilled(false);
        reporteEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteEntradaActionPerformed(evt);
            }
        });
        jPanel1.add(reporteEntrada);
        reporteEntrada.setBounds(300, 380, 160, 60);

        reporteNovedad.setBackground(new java.awt.Color(255, 255, 255));
        reporteNovedad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/imgReporte.png"))); // NOI18N
        reporteNovedad.setContentAreaFilled(false);
        reporteNovedad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporteNovedadActionPerformed(evt);
            }
        });
        jPanel1.add(reporteNovedad);
        reporteNovedad.setBounds(60, 380, 160, 60);

        jPanel2.setOpaque(false);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel1.setText("Fecha inicial");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 129, 45));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel2.setText("Fecha final");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 100, 57));
        jPanel2.add(jDateChooserInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 170, 38));
        jPanel2.add(jDateChooserFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 170, 37));

        mensaje.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        mensaje.setForeground(new java.awt.Color(204, 0, 0));
        mensaje.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(mensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 440, 60));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 170, 480, 200);

        jL_fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoSalida.jpg"))); // NOI18N
        jPanel1.add(jL_fondo);
        jL_fondo.setBounds(0, 0, 530, 520);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 546, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(518, 547));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void reporteEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteEntradaActionPerformed
        try {
            mensaje.setText("");
            if (validarEntrada()) {

                cr = new ControlReporte(fechaInicial, fechaFinal);
                if (cr.contarRegistrosEntradas() > 0) {
                    cr.crearExcelEntradas();
                    new MostrarMensaje("Reporte creado", null, true);
                    dispose();
                } else {
                    mensaje.setText("No existen registros");
                }
            }

        } catch (Exception ex) {
            Logger.getLogger(Reporte.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_reporteEntradaActionPerformed

    private void reporteNovedadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporteNovedadActionPerformed
        try {
            mensaje.setText("");
            if (validarEntrada()) {

                cr = new ControlReporte(fechaInicial, fechaFinal);
                if (cr.contarRegistrosNovedades() > 0) {
                    cr.crearExcelNovedades();
                    new MostrarMensaje("Reporte creado", null, true);
                    dispose();
                } else {
                    mensaje.setText("No existen registros");
                }
            }

        } catch (Exception ex) {
            Logger.getLogger(Reporte.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_reporteNovedadActionPerformed

    public boolean validarEntrada() throws ParseException {
        boolean validar = false;
        if (jDateChooserInicial.getDate() == null || jDateChooserFinal.getDate() == null) {

            mensaje.setText("Ingrese El rango De Fechas");
        } else {
            validar = true;
            llamarFechas();
            mensaje.setText("");

        }

        return validar;
    }

    public void llamarFechas() throws ParseException {
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat formato2 = new SimpleDateFormat("yyyy-MM-dd");
        fechaInicial = formato.format(jDateChooserInicial.getDate());
        fechaFinal = formato2.format(jDateChooserFinal.getDate());

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel Reporte;
    private com.toedter.calendar.JDateChooser jDateChooserFinal;
    private com.toedter.calendar.JDateChooser jDateChooserInicial;
    private javax.swing.JLabel jL_fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel mensaje;
    private javax.swing.JButton reporteEntrada;
    private javax.swing.JButton reporteNovedad;
    // End of variables declaration//GEN-END:variables
}
